server:
  port: 8082
spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/school?characterEncoding=utf8&useSSL=false
    username: root
    password: root

# 设置日志级别
logging:
  level.root: info
  level.cn.nianzuochen.reportform: debug
